const mongoose=require('mongoose');
const Schema=mongoose.Schema;
const ridebookingSchema=new Schema(
    {
        pickup_lat:{
          type:Number,
      },
      pickup_lng:{
          type:Number,
      },
      category:[
          {
              type:String
          }
      ],
      drop_lat:{
        type:Number, 
      },
      drop_lng:{
        type:Number, 
      },
      pickup_mode:[
          {
              type:String
          }
      ],
      payment_instrument_type:[
          {
              type:String
          }
      ],
      fare_id:{
          type:String
      },
      affiliate_uid:{
        type:String
    },
    coupon_code:{
         type:String  
    },
    merchant_txn_id:{
         type:String
    },
    booking_id:{
        type:String
    },
      x_app_token:{
        type:String
      },
      authorization:{
          type:String
      },
      content_type:{
          type:String
      }
    },
    {
        timestamps:true,
    }
);
const RideBooking=mongoose.model('RideBooking',ridebookingSchema);
module.exports=RideBooking;