const mongoose=require('mongoose');
const Schema=mongoose.Schema;
const vehicleSchema=new Schema(
    {
      vehiclename:{
          type:String
      },
      vehicletype:{
          type:String
      },
      vehicleicon:{
        type:String
    },
    seatingcapacity:{
        type:String
    },
    pricinglogic:{
            type:String
        },
    initialwaitingtime:{
        type:String
      },
      additionalwaitingtime:
          {
              type:String
          },
          baseprice:{
              type:String
          },
          fareperkm:{
                type:String
            },
           ridetimecharges:{
                type:String
            },
            waitingfare:{
                type:String
            },
          minimumdistance:{
              rentalplans:{
                 onehr15km:{
                     type:String
                 },
                 twohr30km:{
                     type:String
                 },
                 fourhr40km:{
                     type:String
                 },
                 eighthr80km:{
                     type:String
                 }
              }
          },
         outstation:{
             basekm180for12hr:{
                basepriceperday180:{
                    type:String
                },
                after180km:{
                    type:String
                },
                dailyallowance180:{
                    type:String
                },
                bookingfees180:{
                    type:String
                },
                taxes180:{
                    type:String
                }
             },
             basekm250for24hr:{
                basepriceperday250:{
                    type:String
                },
                after250km:{
                    type:String
                },
                dailyallowance250:{
                    type:String
                },
                bookingfees250:{
                    type:String
                },
                taxes250:{
                    type:String
                }
             }
         }
    },

    {
        timestamps:true,
    }
);
const Vehicle=mongoose.model('Vehicle',vehicleSchema);
module.exports=Vehicle;